"""add labels, due_date, epic status and position

Revision ID: 1554f125bee0
Revises: c08b6a3f6593
Create Date: 2026-04-07 21:10:12.182690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1554f125bee0'
down_revision = 'c08b6a3f6593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_item_labels',
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_item_id', 'label_id')
    )
    with op.batch_alter_table('epic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='to_do', nullable=False))
        batch_op.add_column(sa.Column('position', sa.Integer(), server_default='0', nullable=True))

    with op.batch_alter_table('work_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_item', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('epic', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('status')

    op.drop_table('work_item_labels')
    op.drop_table('label')
    # ### end Alembic commands ###
