"""Add initial_committed_sp to sprint

Revision ID: 1c59f8814b48
Revises: 50a63695cd46
Create Date: 2026-04-14 21:55:28.102803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c59f8814b48'
down_revision = '50a63695cd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_committed_sp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_column('initial_committed_sp')

    # ### end Alembic commands ###
