"""add story_points to work_item

Revision ID: 70a3252ee345
Revises: 29f302b1dcb3
Create Date: 2026-04-06 00:38:06.169911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a3252ee345'
down_revision = '29f302b1dcb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_item', schema=None) as batch_op:
        batch_op.drop_column('story_points')

    # ### end Alembic commands ###
