"""Add display_name, default_assignee, board_sprint_filter to User

Revision ID: 7f89311f7f1a
Revises: 70a3252ee345
Create Date: 2026-04-06 18:35:18.836055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f89311f7f1a'
down_revision = '70a3252ee345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_assignee', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('board_sprint_filter', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('board_sprint_filter')
        batch_op.drop_column('default_assignee')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
