"""add count_cancelled_as_completed to project

Revision ID: 964e233f68b8
Revises: e57b08df3c18
Create Date: 2026-04-17 11:41:18.670474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964e233f68b8'
down_revision = 'e57b08df3c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_cancelled_as_completed', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('count_cancelled_as_completed')

    # ### end Alembic commands ###
