"""Add velocity snapshot columns to sprint

Revision ID: c08b6a3f6593
Revises: 7f89311f7f1a
Create Date: 2026-04-06 20:48:43.988558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08b6a3f6593'
down_revision = '7f89311f7f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('committed_sp_snapshot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_sp_snapshot', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_column('completed_sp_snapshot')
        batch_op.drop_column('committed_sp_snapshot')
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
